# Generated by Django 4.1 on 2022-08-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adddress',
        ),
        migrations.AddField(
            model_name='customer_address',
            name='customer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='sales.customer'),
        ),
    ]
