# Generated by Django 4.1 on 2022-08-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_customer_adddress_customer_address_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='quote_items',
        ),
        migrations.AddField(
            model_name='quote_items',
            name='quotation',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='sales.quotation'),
        ),
    ]
