# Generated by Django 4.1 on 2022-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_customer_address_arabic_bdnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='display_name_arabic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
